{
  "formatVersion": "1.1",
  "component": {
    "group": "io.codechicken",
    "module": "DiffPatch",
    "version": "2.0.0.35",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.covers1624",
          "module": "Quack",
          "version": {
            "requires": "0.4.10.101"
          }
        },
        {
          "group": "it.unimi.dsi",
          "module": "fastutil",
          "version": {
            "requires": "8.3.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.9"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.18"
          }
        },
        {
          "group": "org.tukaani",
          "module": "xz",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "net.sf.jopt-simple",
          "module": "jopt-simple",
          "version": {
            "requires": "5.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "DiffPatch-2.0.0.35.jar",
          "url": "DiffPatch-2.0.0.35.jar",
          "size": 135737,
          "sha512": "2330efafee5ce69836fb494987e5a0bd1148c3c83def536874cdd533944d101d08b22ddfb810bd3f43a25ff11b84994cfd409e20ea225799d6e4b8d8009c7bb9",
          "sha256": "908d8ce97c54e0d4230e993fa4d6fd6b06552f6da1a8fe9d9aa625361e8ed2aa",
          "sha1": "a4527d45e640a7807a3b68ff0cf668c4a1bc434b",
          "md5": "39905c56b7ef4afb606151fe7ba65d8e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.covers1624",
          "module": "Quack",
          "version": {
            "requires": "0.4.10.101"
          }
        },
        {
          "group": "it.unimi.dsi",
          "module": "fastutil",
          "version": {
            "requires": "8.3.1"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.9"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.18"
          }
        },
        {
          "group": "org.tukaani",
          "module": "xz",
          "version": {
            "requires": "1.8"
          }
        },
        {
          "group": "net.sf.jopt-simple",
          "module": "jopt-simple",
          "version": {
            "requires": "5.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "DiffPatch-2.0.0.35.jar",
          "url": "DiffPatch-2.0.0.35.jar",
          "size": 135737,
          "sha512": "2330efafee5ce69836fb494987e5a0bd1148c3c83def536874cdd533944d101d08b22ddfb810bd3f43a25ff11b84994cfd409e20ea225799d6e4b8d8009c7bb9",
          "sha256": "908d8ce97c54e0d4230e993fa4d6fd6b06552f6da1a8fe9d9aa625361e8ed2aa",
          "sha1": "a4527d45e640a7807a3b68ff0cf668c4a1bc434b",
          "md5": "39905c56b7ef4afb606151fe7ba65d8e"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "DiffPatch-2.0.0.35-all.jar",
          "url": "DiffPatch-2.0.0.35-all.jar",
          "size": 22580403,
          "sha512": "5461682a449609f07e81d56a1e5862759476fe87014743eafbd46e750edb6177e940c4aa65c564515989deb6139bdf87fd3766f5779794229064a546a0b2d00e",
          "sha256": "a69b86a83e1335ec34bbf2e7498c3c55e4882169a3853a480c9b0fdbafdee646",
          "sha1": "8ad2c6effed4c90641e6ac440d5861a0370776a6",
          "md5": "71cb6a738bde0828cbab08fd270523a8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "DiffPatch-2.0.0.35-sources.jar",
          "url": "DiffPatch-2.0.0.35-sources.jar",
          "size": 48999,
          "sha512": "c2a0416cd577c888f0d57d5bd7d67abd7406fa4b8a87e87040e72e4ec9a4a8628bbfa39737a94a59730b97045ba918965438d9099577822a5fe0320952bbf188",
          "sha256": "4f0a9a5dfbe37b8d8b64bc8ad89fa2c84160b0dcb342caaf9152b2504e1683b5",
          "sha1": "0e97190d9cbc5189e5c41ffe877b44516d3d3f65",
          "md5": "936d45b90df3229dfb677885825e0c04"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "DiffPatch-2.0.0.35-javadoc.jar",
          "url": "DiffPatch-2.0.0.35-javadoc.jar",
          "size": 230626,
          "sha512": "f02f274c5e4cf73b041232c862f728482168da4b0a877aeee4e51d7096ee9f5f34d7407d488e93213ae4a212ba4623eea85dc1b0ac36587d1cbf4c039e68ee46",
          "sha256": "2b93b3cf85f06974ca707da5dfce6356ae2cad1470842ab458b25fbf0caff448",
          "sha1": "9be728564dc75d5f3ca0099e4db4a45afbfae435",
          "md5": "0203d5b9d6c1fee440892fff45f296f6"
        }
      ]
    }
  ]
}
