{
  "formatVersion": "1.1",
  "component": {
    "group": "net.neoforged",
    "module": "groovydslimprover",
    "version": "2.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "groovydslimprover-2.0.0.jar",
          "url": "groovydslimprover-2.0.0.jar",
          "size": 132660,
          "sha512": "25bb9f13d5984a9c47774e2987d2b7625699d88f9e6f0c30fba287991f7ca137c6f2a73f5a6b9e4d791a991344043488f01001ec6dc39d71b46f4b069c19ed53",
          "sha256": "4877d771b49b3e47f1df221152f8bb77dbbb649737aef5a09353e1c41487a6d8",
          "sha1": "9ef57a217b6a814d12d6b8932d98f01f2024b8dc",
          "md5": "48062ed12d3f195c606d89c3fe595da6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "groovydslimprover-2.0.0.jar",
          "url": "groovydslimprover-2.0.0.jar",
          "size": 132660,
          "sha512": "25bb9f13d5984a9c47774e2987d2b7625699d88f9e6f0c30fba287991f7ca137c6f2a73f5a6b9e4d791a991344043488f01001ec6dc39d71b46f4b069c19ed53",
          "sha256": "4877d771b49b3e47f1df221152f8bb77dbbb649737aef5a09353e1c41487a6d8",
          "sha1": "9ef57a217b6a814d12d6b8932d98f01f2024b8dc",
          "md5": "48062ed12d3f195c606d89c3fe595da6"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "groovydslimprover-2.0.0-javadoc.jar",
          "url": "groovydslimprover-2.0.0-javadoc.jar",
          "size": 370,
          "sha512": "0da3ae49eb4962a5531ef7e354241ee830487932eebae72c9b16506f03e753e6ef241b654c318b46d24db488b61e6b8b8b531e300e50694f566d2efcdafba25b",
          "sha256": "159af3264bfa0669750cfef2bb467c09c932db8d2b54eb2e4c7678d642d5be8a",
          "sha1": "7d62b901497626bea218e4a6209159e2c8887755",
          "md5": "14f8162b22b54cc679a68de957988d86"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "groovydslimprover-2.0.0-sources.jar",
          "url": "groovydslimprover-2.0.0-sources.jar",
          "size": 22760,
          "sha512": "d108365f5a1d010625b5219f123c5f51631a2871114bc7b400ede42c229e6bef90b5cc75ec8a01ccd782826ac6c4ff03059ce15cc48350f3344c8b9ff528bad3",
          "sha256": "ff31d557822aa93787699d0074fe76f3b7e2252a3ddd0174e02da2baa808a974",
          "sha1": "3361e5b9b860b1f4eed170417f5be854f7e44f85",
          "md5": "5ea1b04bd6b6c45d9f3755b75e0ab69d"
        }
      ]
    },
    {
      "name": "runtimeJavadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "groovydslimprover-2.0.0-runtime-javadoc.jar",
          "url": "groovydslimprover-2.0.0-runtime-javadoc.jar",
          "size": 86138,
          "sha512": "42518c2ab1cf4aa05afd975941a0f40823788d29b20d25cab03d247664ddc3b1f1fe83da89f939fe96e510ba86087bbf04104bf2a98daba31cb94c460160fe24",
          "sha256": "8881e1e77a316088765060e0ab9b62096f715dc94daf8b8811a085a61e495754",
          "sha1": "c501ede1641075d65fa2d54932f1367931d23282",
          "md5": "945b6318364121fa83716d5250f4c4d3"
        }
      ],
      "capabilities": [
        {
          "group": "net.neoforged",
          "name": "groovydslimprover-runtime",
          "version": "2.0.0"
        }
      ]
    },
    {
      "name": "runtimeSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "groovydslimprover-2.0.0-runtime-sources.jar",
          "url": "groovydslimprover-2.0.0-runtime-sources.jar",
          "size": 2675,
          "sha512": "57f346c3bd072489b1a1ecc687fb7f812ff741eb6934740a75605b43e07b0f030e82177fc6191c09475a3bdd96176d13d92d34ab8c7dfb07898eb12807e7991a",
          "sha256": "0d7c9a9d134c6a3f303ed311cff6fdb77cd3c4d9408377b62e1734a27157378c",
          "sha1": "72c511fae811333616c3762975756dc85634372c",
          "md5": "d180a0e108de56e6daa3a9370a5b792f"
        }
      ],
      "capabilities": [
        {
          "group": "net.neoforged",
          "name": "groovydslimprover-runtime",
          "version": "2.0.0"
        }
      ]
    },
    {
      "name": "runtimeApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "groovydslimprover-2.0.0-runtime.jar",
          "url": "groovydslimprover-2.0.0-runtime.jar",
          "size": 4500,
          "sha512": "b31caa3860be9988e6ed233808cd19268e0634f4ae36f3cb6d877f690ae739f5c13104065b26f6c2e92e7ddb49fd100a6376eb69a3f67808e9068cce55d380f6",
          "sha256": "f04c9be99ab6380bff94a3ba3364113b79db5774d267e47c208c591d6c870a11",
          "sha1": "9453dbe95a9aaa048fdc168339d28a05947bb57e",
          "md5": "47e11b32e06fc264704beca053156ad1"
        }
      ],
      "capabilities": [
        {
          "group": "net.neoforged",
          "name": "groovydslimprover-runtime",
          "version": "2.0.0"
        }
      ]
    },
    {
      "name": "runtimeRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "groovydslimprover-2.0.0-runtime.jar",
          "url": "groovydslimprover-2.0.0-runtime.jar",
          "size": 4500,
          "sha512": "b31caa3860be9988e6ed233808cd19268e0634f4ae36f3cb6d877f690ae739f5c13104065b26f6c2e92e7ddb49fd100a6376eb69a3f67808e9068cce55d380f6",
          "sha256": "f04c9be99ab6380bff94a3ba3364113b79db5774d267e47c208c591d6c870a11",
          "sha1": "9453dbe95a9aaa048fdc168339d28a05947bb57e",
          "md5": "47e11b32e06fc264704beca053156ad1"
        }
      ],
      "capabilities": [
        {
          "group": "net.neoforged",
          "name": "groovydslimprover-runtime",
          "version": "2.0.0"
        }
      ]
    },
    {
      "name": "baseJavadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "groovydslimprover-2.0.0-base-javadoc.jar",
          "url": "groovydslimprover-2.0.0-base-javadoc.jar",
          "size": 370,
          "sha512": "0da3ae49eb4962a5531ef7e354241ee830487932eebae72c9b16506f03e753e6ef241b654c318b46d24db488b61e6b8b8b531e300e50694f566d2efcdafba25b",
          "sha256": "159af3264bfa0669750cfef2bb467c09c932db8d2b54eb2e4c7678d642d5be8a",
          "sha1": "7d62b901497626bea218e4a6209159e2c8887755",
          "md5": "14f8162b22b54cc679a68de957988d86"
        }
      ],
      "capabilities": [
        {
          "group": "net.neoforged",
          "name": "groovydslimprover-base",
          "version": "2.0.0"
        }
      ]
    },
    {
      "name": "baseSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "groovydslimprover-2.0.0-base-sources.jar",
          "url": "groovydslimprover-2.0.0-base-sources.jar",
          "size": 4124,
          "sha512": "26e171a420467dadbad9e60a6d939ca8ec55c68f71db63d2a9ee502984ccf8c9c5ce95b2208991679aa68dc678e227572eabf6c0bd129b56cd2251110c97b34c",
          "sha256": "b8828f6e335ecc4e4cd617d4b178177b4e9ab0fd51d29c4f4e1db7e0946d8528",
          "sha1": "c2d162e1223b0fe66fa4b2e05f9e483579aa16e8",
          "md5": "69dc5023f438efc7486bd4a35a24b8c3"
        }
      ],
      "capabilities": [
        {
          "group": "net.neoforged",
          "name": "groovydslimprover-base",
          "version": "2.0.0"
        }
      ]
    },
    {
      "name": "baseApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.neoforged",
          "module": "groovydslimprover",
          "version": {
            "requires": "2.0.0"
          },
          "requestedCapabilities": [
            {
              "group": "net.neoforged",
              "name": "groovydslimprover-runtime"
            }
          ]
        },
        {
          "group": "net.neoforged",
          "module": "groovydslimprover",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "groovydslimprover-2.0.0-base.jar",
          "url": "groovydslimprover-2.0.0-base.jar",
          "size": 6067,
          "sha512": "4e712373c9f64dffc57d27bf7153efb3b79370efea9135e11085c8403519b3a5cbdc5baa31a0a01930c9780c9cf88c4386a38b45cc7a5c7d6560241af1036594",
          "sha256": "b5b74b4e43fa64a44dfbc4b139ca56796fdf284ac58d23df3f560978ad258cf3",
          "sha1": "21b76c4963e260fd8ea0e18e51052af9d12418a7",
          "md5": "b9aa70d0d47347ef9820f6e53c123bac"
        }
      ],
      "capabilities": [
        {
          "group": "net.neoforged",
          "name": "groovydslimprover-base",
          "version": "2.0.0"
        }
      ]
    },
    {
      "name": "baseRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.neoforged",
          "module": "groovydslimprover",
          "version": {
            "requires": "2.0.0"
          },
          "requestedCapabilities": [
            {
              "group": "net.neoforged",
              "name": "groovydslimprover-runtime"
            }
          ]
        },
        {
          "group": "net.neoforged",
          "module": "groovydslimprover",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "groovydslimprover-2.0.0-base.jar",
          "url": "groovydslimprover-2.0.0-base.jar",
          "size": 6067,
          "sha512": "4e712373c9f64dffc57d27bf7153efb3b79370efea9135e11085c8403519b3a5cbdc5baa31a0a01930c9780c9cf88c4386a38b45cc7a5c7d6560241af1036594",
          "sha256": "b5b74b4e43fa64a44dfbc4b139ca56796fdf284ac58d23df3f560978ad258cf3",
          "sha1": "21b76c4963e260fd8ea0e18e51052af9d12418a7",
          "md5": "b9aa70d0d47347ef9820f6e53c123bac"
        }
      ],
      "capabilities": [
        {
          "group": "net.neoforged",
          "name": "groovydslimprover-base",
          "version": "2.0.0"
        }
      ]
    }
  ]
}
