{
  "formatVersion": "1.1",
  "component": {
    "group": "org.javacord",
    "module": "javacord",
    "version": "3.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.javacord",
          "module": "javacord-api",
          "version": {
            "requires": "3.8.0"
          }
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.javacord",
          "module": "javacord-core",
          "version": {
            "requires": "3.8.0"
          }
        },
        {
          "group": "org.javacord",
          "module": "javacord-api",
          "version": {
            "requires": "3.8.0"
          }
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "javacord-3.8.0-shaded.jar",
          "url": "javacord-3.8.0-shaded.jar",
          "size": 11203249,
          "sha512": "12a5084eb69e746d2950cc10d39361d8439571849f00b414ce305b6ad9587238e7705f78ac39720dae02f44256e7fadb9381ef3fe9a5745f0e62fa2548073dfc",
          "sha256": "e3e9f15a31dff2ab834163b87e4738a56671962d5f423fbf8c8b857e6b7923c4",
          "sha1": "68b9211520c1ee506a48375d03fdac8781969cab",
          "md5": "36c036a72c1d38fbf1f57a314d2a0803"
        }
      ]
    }
  ]
}
