{
  "formatVersion": "1.1",
  "component": {
    "group": "de.siegmar",
    "module": "fastcsv",
    "version": "2.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9",
      "buildId": "7xu2k7yhwvdgtmmdw3uo6pejs4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "fastcsv-2.2.0.jar",
          "url": "fastcsv-2.2.0.jar",
          "size": 32003,
          "sha512": "bf0ae48f797575f5ab943614684c6b6947ac79dfbd0dcc08978445b3ff2a7e73c2ae31c925c11782cbb2ed82946b607422c4d0e5293d6f5cf04a6c637b859946",
          "sha256": "af236af10939ed6a25fccf4e8266a5c90eec2e0b2e3354983cb2db3011a2ccd8",
          "sha1": "d38ad4d6e2c3d007f9ca8f3287b0db51d4bf4537",
          "md5": "552cf5b0275b887709221e91049795a8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fastcsv-2.2.0.jar",
          "url": "fastcsv-2.2.0.jar",
          "size": 32003,
          "sha512": "bf0ae48f797575f5ab943614684c6b6947ac79dfbd0dcc08978445b3ff2a7e73c2ae31c925c11782cbb2ed82946b607422c4d0e5293d6f5cf04a6c637b859946",
          "sha256": "af236af10939ed6a25fccf4e8266a5c90eec2e0b2e3354983cb2db3011a2ccd8",
          "sha1": "d38ad4d6e2c3d007f9ca8f3287b0db51d4bf4537",
          "md5": "552cf5b0275b887709221e91049795a8"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fastcsv-2.2.0-javadoc.jar",
          "url": "fastcsv-2.2.0-javadoc.jar",
          "size": 67970,
          "sha512": "cf5114d37aaf8c3913bae7cf6e721afa0f2c8ca47dc01e62dfe1b07d624c2585aebe3560af8237e44c4a5fce46b80efc3af385b1700d073fc9d4e1076904f314",
          "sha256": "8a8e9e6f654f47bb63f53e1602f0212d74716e526851295593a1b49cd7507626",
          "sha1": "21accf0241700b52cc2236a3786eaf783cfb5430",
          "md5": "8945186c6928d8c05cf760dd46440f89"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fastcsv-2.2.0-sources.jar",
          "url": "fastcsv-2.2.0-sources.jar",
          "size": 20103,
          "sha512": "12cba44bff8041feda879d0053203195234c33b6e5174be61d1c77c222e186f5ff31a02a84a35c5d2ab55b726c06bb4975aefabac4419caa1954402baa5d4a48",
          "sha256": "040765cac68a75910b361cf6620d174291cb8c099dfbde30a206cd1a5217e8c8",
          "sha1": "a3221dc6e28c3d4ca4f9ce02ba17e44f635dd935",
          "md5": "2a576a893d01ab7400474d9c1353596f"
        }
      ]
    }
  ]
}
