{
  "formatVersion": "1.1",
  "component": {
    "group": "net.fabricmc",
    "module": "fabric-loom",
    "version": "1.11-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "8.14",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "fabric-loom-1.11-SNAPSHOT.jar",
          "url": "fabric-loom-1.11-SNAPSHOT.jar",
          "size": 1159795,
          "sha512": "b7b7065ed86a2de664a4850f510290d8492d7d87cdb78f6e8e4da16fd33f9296ba8de4062336d6eb355c8b0c468baa52bad5f9a74c977d3b560a41cfee3c117d",
          "sha256": "1517a1b9fabccdc4f0df29846b9cfbcf2dbf6a361004c8ede509309f4b28c7b4",
          "sha1": "b50d1289e772f60ae999a70768edb3f9f099f0a6",
          "md5": "4b725994e712bc2af69ece1a69c9c42a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.plugin.api-version": "8.14",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.15.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.0.0-jre"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.8"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-analysis",
          "version": {
            "requires": "9.8"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.8"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.8"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.8"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "stitch",
          "version": {
            "requires": "0.6.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "enigma"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "tiny-remapper",
          "version": {
            "requires": "0.11.1"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "access-widener",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "mapping-io",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "lorenz-tiny",
          "version": {
            "requires": "4.0.2"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loom-native",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "mercury",
          "version": {
            "requires": "0.4.2"
          }
        },
        {
          "group": "net.fabricmc.unpick",
          "module": "unpick",
          "version": {
            "requires": "3.0.0-beta.9"
          }
        },
        {
          "group": "net.fabricmc.unpick",
          "module": "unpick-format-utils",
          "version": {
            "requires": "3.0.0-beta.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-metadata-jvm",
          "version": {
            "requires": "2.0.21"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "fabric-loom-1.11-SNAPSHOT.jar",
          "url": "fabric-loom-1.11-SNAPSHOT.jar",
          "size": 1159795,
          "sha512": "b7b7065ed86a2de664a4850f510290d8492d7d87cdb78f6e8e4da16fd33f9296ba8de4062336d6eb355c8b0c468baa52bad5f9a74c977d3b560a41cfee3c117d",
          "sha256": "1517a1b9fabccdc4f0df29846b9cfbcf2dbf6a361004c8ede509309f4b28c7b4",
          "sha1": "b50d1289e772f60ae999a70768edb3f9f099f0a6",
          "md5": "4b725994e712bc2af69ece1a69c9c42a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.plugin.api-version": "8.14",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fabric-loom-1.11-SNAPSHOT-sources.jar",
          "url": "fabric-loom-1.11-SNAPSHOT-sources.jar",
          "size": 660503,
          "sha512": "b1298ce6b7207f2cfa4a905155add34b21760d269bd24fa8f0c92e9622187d3be8d3ada7b400f4643495dd14abd377d7a6205ebc9c04e547932db49c85d0d076",
          "sha256": "7edb69d4017fecaa46d0c83ea3eb171b77fb27ee83c47d647bd3cacfd0be0343",
          "sha1": "36dcb9e83e9b458751c9af31ccb4d407ccb6657e",
          "md5": "f7fe601f8d0a6e2a9042bb5fdf29797f"
        }
      ]
    }
  ]
}
